In [1]:
#### Chap 1.3.1 Basic Operations on Images

In [2]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [3]:
img = cv2.imread('cat.jpg')

In [4]:
plt.imshow(img, cmap = 'gray', interpolation = 'bicubic')
plt.xticks([]), plt.yticks([])
plt.show()

In [5]:
cv2.namedWindow('image', cv2.WINDOW_NORMAL)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllwindows()

AttributeError: module 'cv2' has no attribute 'destroyAllwindows'

In [ ]:
img.shape

(182, 277, 3)

In [51]:
img[100, 100]

array([172, 191, 206], dtype=uint8)

In [52]:
img[100, 100, 0]=0

In [53]:
img[100, 100]

array([  0, 191, 206], dtype=uint8)

In [54]:
img[100,100]=0,0,0

In [55]:
img[0:10, 0:10]

array([[[ 3, 17, 13],
        [ 3, 17, 13],
        [ 3, 17, 13],
        [ 3, 17, 13],
        [ 2, 17, 13],
        [ 2, 17, 13],
        [ 0, 17, 13],
        [ 0, 17, 13],
        [12, 29, 25],
        [11, 28, 24]],

       [[ 3, 17, 13],
        [ 3, 17, 13],
        [ 3, 17, 13],
        [ 3, 17, 13],
        [ 2, 17, 13],
        [ 2, 17, 13],
        [ 0, 17, 13],
        [ 0, 17, 13],
        [11, 28, 24],
        [10, 27, 23]],

       [[ 4, 18, 14],
        [ 4, 18, 14],
        [ 4, 18, 14],
        [ 4, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 9, 26, 22],
        [ 8, 25, 21]],

       [[ 4, 18, 14],
        [ 4, 18, 14],
        [ 4, 18, 14],
        [ 4, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 6, 23, 19],
        [ 6, 23, 19]],

       [[ 7, 18, 15],
        [ 7, 18, 15],
        [ 5, 19, 15],
        [ 5, 19, 15],
        [ 5, 19, 15],
  

In [56]:
img[0:10, 0:10]=[0,0,0]

array([[[ 3, 17, 13],
        [ 3, 17, 13],
        [ 3, 17, 13],
        [ 3, 17, 13],
        [ 2, 17, 13],
        [ 2, 17, 13],
        [ 0, 17, 13],
        [ 0, 17, 13],
        [12, 29, 25],
        [11, 28, 24]],

       [[ 3, 17, 13],
        [ 3, 17, 13],
        [ 3, 17, 13],
        [ 3, 17, 13],
        [ 2, 17, 13],
        [ 2, 17, 13],
        [ 0, 17, 13],
        [ 0, 17, 13],
        [11, 28, 24],
        [10, 27, 23]],

       [[ 4, 18, 14],
        [ 4, 18, 14],
        [ 4, 18, 14],
        [ 4, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 9, 26, 22],
        [ 8, 25, 21]],

       [[ 4, 18, 14],
        [ 4, 18, 14],
        [ 4, 18, 14],
        [ 4, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 3, 18, 14],
        [ 6, 23, 19],
        [ 6, 23, 19]],

       [[ 7, 18, 15],
        [ 7, 18, 15],
        [ 5, 19, 15],
        [ 5, 19, 15],
        [ 5, 19, 15],
  

In [ ]:
img[60:80, 60:80, 0]= 0